# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('listing_date', models.DateTimeField(verbose_name='date listed')),
                ('listing_price', models.PositiveIntegerField()),
            ],
        ),
    ]
