# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twohomez', '0003_home_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='num_bathrooms',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='num_bedrooms',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
