# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twohomez', '0004_auto_20170423_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='listing_date',
        ),
    ]
