# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twohomez', '0005_remove_home_listing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='neighborhood',
            field=models.CharField(choices=[('Seacliff', 'Seacliff'), ('Haight Ashbury', 'Haight Ashbury'), ('Outer Mission', 'Outer Mission'), ('Downtown/Civic Center', 'Civic Center'), ('Diamond Heights', 'Diamond Heights'), ('Lakeshore', 'Lakeshore'), ('Russian Hill', 'Russian Hill'), ('Noe Valley', 'Noe Valley'), ('Inner Sunset', 'Inner Sunset'), ('Treasure Island/YBI', 'Treasure Island'), ('Outer Richmond', 'Outer Richmond'), ('Crocker Amazon', 'Crocker Amazon'), ('Excelsior', 'Excelsior'), ('Parkside', 'Parkside'), ('Financial District', 'Financial District'), ('Ocean View', 'Ocean View'), ('Mission', 'Mission'), ('West of Twin Peaks', 'West of Twin Peaks'), ('Inner Richmond', 'Inner Richmond'), ('Marina', 'Marina'), ('Bayview', 'Bayview'), ('Visitacion Valley', 'Visitacion Valley'), ('Pacific Heights', 'Pacific Heights'), ('Presidio Heights', 'Presidio Heights'), ('South of Market', 'SoMa'), ('Glen Park', 'Glen Park'), ('Potrero Hill', 'Potrero Hill'), ('Castro/Upper Market', 'Castro/Upper Market'), ('Twin Peaks', 'Twin Peaks'), ('Bernal Heights', 'Bernal Heights'), ('Chinatown', 'Chinatown'), ('North Beach', 'North Beach'), ('Presidio', 'Presidio'), ('Nob Hill', 'Nob Hill'), ('Outer Sunset', 'Outer Sunset'), ('Western Addition', 'Western Addition'), ('Golden Gate Park', 'Golden Gate Park')], default='Seacliff', max_length=30),
            preserve_default=False,
        ),
    ]
