# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twohomez', '0008_home_sale_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='address',
            new_name='address0',
        ),
        migrations.AddField(
            model_name='home',
            name='address1',
            field=models.CharField(default='e', max_length=200),
            preserve_default=False,
        ),
    ]
