# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twohomez', '0010_auto_20170423_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='zillow_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
