# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twohomez', '0011_home_zillow_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='mortgage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
