# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twohomez', '0013_auto_20170427_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='fall_rent_day',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='spring_rent_day',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='summer_rent_day',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='winter_rent_day',
            field=models.FloatField(null=True),
        ),
    ]
